package com.iris.earsiv.model.file;

public enum FileCategory {
    ISGTF1A("FIRMA BILGILERI"),
    ISGTF2B("YILLIK CALISMA PLANI"),
    ISGTF3C("YILLIK DEGERLENDIRME RAPORU"),
    ISGTF4D("CALISAN TEMSILCILERINE ILISKIN DOKUMANLAR"),
    ISGTF5E("RISK DEGERLENDIRMESINE ILISKIN DOKUMANLAR"),
    ISGTF6F("ACIL DURUMLARA ILISKIN DOKUMANLAR"),
    ISGTF7G("PERIYODIK KONTROLLER VE ORTAM OLCUMLERINE ILISKIN DOKUMANLAR"),
    ISGTF8H("KIMYASAL MADDELERE ILISKIN DOKUMANLAR"),
    ISGTF9I("KISISEL KORUYUCU DONANIMLARA ILISKIN DOKUMANLAR"),
    ISGTF10J("SAGLIK VE GUVENLIK ISARETLERINE ILISKIN DOKUMANLAR"),
    ISGTF11K("TALIMATLAR"),
    ISGTF12L("SAGLIK KAYITLARI"),
    ISGTF13M("EGITIMLERE ILISKIN DOKUMANLAR"),
    ISGTF14N("IS SAGLIGI VE GUVENLIGI KURALLARINA ILISKIN DOKUMANLAR"),
    ISGTF15O("IS KAZASI - MESLEK HASTALIGI - RAMAK KALA KAYITLARI"),
    ISGTF16P("DENETIM RAPORLARI"),
    ISGTF17R("PUANTAJ KAYITLARI"),
    ISGTF18S("ONAYLI DEFTER SURETLERI"),
    ISGTF19T("DIGER DOKUMANLAR");


    private String name;

    FileCategory(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }
}
